package VistaR;

import ControladorR.ControladorGenerarNumero;
import ControladorR.ControladorOrdenar;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.TransferHandler;

public class PrincipalRana extends javax.swing.JFrame {

    int numeroEntradas = 1;

    public PrincipalRana() {
        initComponents();
        setLocationRelativeTo(null);
        Gif.setVisible(false);
        Texto.setVisible(false);
        Roca1.setVisible(false);
        Roca2.setVisible(false);
        Roca3.setVisible(false);
        Roca4.setVisible(false);

    }

    public void transferirTexto(JLabel nub, JLabel roc) {
        nub.setTransferHandler(new TransferHandler("text"));
        roc.setTransferHandler(new TransferHandler("text"));

        MouseListener ml = new MouseAdapter() {
            //creamos el método para transferir
            //datos al presionar con el ratón

            public void mousePressed(MouseEvent e) {
                JComponent jc = (JComponent) e.getSource();
                TransferHandler th = jc.getTransferHandler();
                th.exportAsDrag(jc, e, TransferHandler.COPY);

            }
        };
        nub.addMouseListener(ml);
        roc.addMouseListener(ml);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RanaxRocaL = new javax.swing.JLabel();
        ro1 = new javax.swing.JLabel();
        ro2 = new javax.swing.JLabel();
        ro3 = new javax.swing.JLabel();
        ro4 = new javax.swing.JLabel();
        num1 = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        num3 = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        Roca1 = new javax.swing.JLabel();
        Roca2 = new javax.swing.JLabel();
        Roca4 = new javax.swing.JLabel();
        Nube3 = new javax.swing.JLabel();
        Roca3 = new javax.swing.JLabel();
        forden = new javax.swing.JLabel();
        Gif = new javax.swing.JLabel();
        Nube4 = new javax.swing.JLabel();
        Nube1 = new javax.swing.JLabel();
        Nube2 = new javax.swing.JLabel();
        TITULO = new javax.swing.JLabel();
        Texto = new javax.swing.JLabel();
        terminar = new javax.swing.JLabel();
        jugar = new javax.swing.JLabel();
        pergamino = new javax.swing.JLabel();
        Estanque = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1375, 745));
        setMinimumSize(new java.awt.Dimension(1375, 745));
        setPreferredSize(new java.awt.Dimension(1375, 745));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RanaxRocaL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/RanaxRoca.png"))); // NOI18N
        getContentPane().add(RanaxRocaL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 180, 160));

        ro1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        ro1.setForeground(new java.awt.Color(1, 1, 1));
        ro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 140, 80));

        ro2.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        ro2.setForeground(new java.awt.Color(1, 1, 1));
        ro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 140, 80));

        ro3.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        ro3.setForeground(new java.awt.Color(1, 1, 1));
        ro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 160, 110));

        ro4.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        ro4.setForeground(new java.awt.Color(1, 1, 1));
        ro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 140, 80));

        num1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        num1.setForeground(new java.awt.Color(1, 1, 1));
        num1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 170, 110));

        num2.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        num2.setForeground(new java.awt.Color(1, 1, 1));
        num2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 170, 110));

        num3.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        num3.setForeground(new java.awt.Color(1, 1, 1));
        num3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 170, 110));

        num4.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        num4.setForeground(new java.awt.Color(1, 1, 1));
        num4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 170, 110));

        Roca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/Rocka2.png"))); // NOI18N
        getContentPane().add(Roca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 160, 80));

        Roca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/Rocka2.png"))); // NOI18N
        getContentPane().add(Roca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, 160, 80));

        Roca4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/Rocka2.png"))); // NOI18N
        getContentPane().add(Roca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 570, 170, 80));

        Nube3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/Nube .png"))); // NOI18N
        Nube3.setText("jLabel1");
        getContentPane().add(Nube3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 170, 110));

        Roca3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/Rocka2.png"))); // NOI18N
        getContentPane().add(Roca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 160, 110));

        forden.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        getContentPane().add(forden, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 280, 40));

        Gif.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        Gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/output_BnuDB1.gif"))); // NOI18N
        getContentPane().add(Gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 990, 290));

        Nube4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/Nube .png"))); // NOI18N
        Nube4.setText("jLabel1");
        getContentPane().add(Nube4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 170, 110));

        Nube1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/Nube .png"))); // NOI18N
        Nube1.setText("jLabel1");
        getContentPane().add(Nube1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 170, 110));

        Nube2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/Nube .png"))); // NOI18N
        Nube2.setText("jLabel1");
        getContentPane().add(Nube2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 170, 110));

        TITULO.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        TITULO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/Titulo2.png"))); // NOI18N
        getContentPane().add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 330, 150));

        Texto.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        Texto.setText("Debes ordenar los numeros de ");
        getContentPane().add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        terminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/arbolTerminar1.png"))); // NOI18N
        terminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                terminarMouseClicked(evt);
            }
        });
        getContentPane().add(terminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 280, -1, -1));

        jugar.setFont(new java.awt.Font("Snap ITC", 1, 48)); // NOI18N
        jugar.setText("JUGAR ");
        jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugarMouseClicked(evt);
            }
        });
        getContentPane().add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 200, -1));

        pergamino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/Letreroccc.png"))); // NOI18N
        getContentPane().add(pergamino, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        Estanque.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Estanque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/estanque1.png"))); // NOI18N
        getContentPane().add(Estanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 1250, 230));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaR/Recursos/Fondito2.jpg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(1375, 745));
        Fondo.setMinimumSize(new java.awt.Dimension(1375, 745));
        Fondo.setOpaque(true);
        Fondo.setPreferredSize(new java.awt.Dimension(1375, 745));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 745));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terminarMouseClicked

        ControladorOrdenar ordenar = ControladorOrdenar.getInstance();
        ordenar.OrdenarNumeros(forden, Roca1, Roca2, Roca3, Roca4, ro1, ro2, ro3, ro4, Nube1, Nube2, Nube3, Nube4, Gif, RanaxRocaL);


    }//GEN-LAST:event_terminarMouseClicked

    private void jugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugarMouseClicked

        ro1.setText("");
        ro2.setText("");
        ro3.setText("");
        ro4.setText("");
        Gif.setVisible(false);
        RanaxRocaL.setVisible(true);
        Roca1.setVisible(true);
        Roca2.setVisible(true);
        Roca3.setVisible(true);
        Roca4.setVisible(true);
        Texto.setVisible(true);

        ControladorGenerarNumero generar = ControladorGenerarNumero.getInstance();
        generar.generadorNumeros(num1, num2, num3, num4, forden);

        transferirTexto(num1, ro1);
        transferirTexto(num2, ro2);
        transferirTexto(num3, ro3);
        transferirTexto(num4, ro4);

        numeroEntradas = numeroEntradas + 1;

        System.out.println("-------" + numeroEntradas);
    }//GEN-LAST:event_jugarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalRana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalRana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalRana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalRana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalRana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Estanque;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Gif;
    private javax.swing.JLabel Nube1;
    private javax.swing.JLabel Nube2;
    private javax.swing.JLabel Nube3;
    private javax.swing.JLabel Nube4;
    private javax.swing.JLabel RanaxRocaL;
    private javax.swing.JLabel Roca1;
    private javax.swing.JLabel Roca2;
    private javax.swing.JLabel Roca3;
    private javax.swing.JLabel Roca4;
    private javax.swing.JLabel TITULO;
    private javax.swing.JLabel Texto;
    private javax.swing.JLabel forden;
    private javax.swing.JLabel jugar;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel num3;
    private javax.swing.JLabel num4;
    private javax.swing.JLabel pergamino;
    private javax.swing.JLabel ro1;
    private javax.swing.JLabel ro2;
    private javax.swing.JLabel ro3;
    private javax.swing.JLabel ro4;
    private javax.swing.JLabel terminar;
    // End of variables declaration//GEN-END:variables

}
